### PR TITLE
Marshal and unmarshal `EXT-X-MAP` and `EXT-X-BYTERANGE` tags

### PR DESCRIPTION
**Pull request by samrat**
- [x] Unmarshal `EXT-X-MAP` tags
- [x] Marshal `EXT-X-MAP` tags. (I'll add this in a separate PR)

Fixes https://github.com/kim-company/kim_hls/issues/13

### CODE REVIEW

**Comment by dmorn** [comment]
Hi @samrat! Sorry for the very late feedback loop, I'll be faster now. Could you please provide some test cases for this feature? Seems a useful addition that fits well in the project's design so we're definitely interested in merging it.

**Comment by samrat** [comment]
👍 Will do!

**Comment by samrat** [comment]
I've pushed tests and changed the scope of this PR to only handle unmarshaling EXT-X-MAP tags. 

When adding tests, I realized that streams using EXT-X-MAP tags are probably going to use EXT-X-BYTERANGE tags as well, so I've also added support for that in this PR.

**Comment by philipgiuliani** [comment]
@samrat Thanks very much for your contribution! We've implemented the marshaling and resolved the last TODOs.

**Comment by samrat** [comment]
👍 Thanks for pushing it over the finishing line, @philipgiuliani !

**Pull request merged**
